doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            BookStore:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/BookStore/Domain'
                prefix: App\BookStore\Domain
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Domain'
                prefix: App\Shared\Domain
            Subscription:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Subscription/Entity'
                prefix: App\Subscription\Entity

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
