monolog:
    channels:
        - deprecation
        - audit
        - subscription

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            audit:
                type: stream
                path: "%kernel.logs_dir%/audit.log"
                level: info
                channels: [audit]
            subscription:
                type: stream
                path: "%kernel.logs_dir%/subscription.log"
                level: info
                channels: [subscription]

when@test:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            audit:
                type: test
                level: info
                channels: [audit]
            subscription:
                type: test
                level: info
                channels: [subscription]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation", "!audit", "!subscription"]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            audit:
                type: stream
                path: "%kernel.logs_dir%/audit.log"
                level: info
                channels: [audit]
                formatter: monolog.formatter.json
            subscription:
                type: stream
                path: "%kernel.logs_dir%/subscription.log"
                level: info
                channels: [subscription]
                formatter: monolog.formatter.json
