name: CI

on:
    push:
        branches: ['main']
    pull_request: ~

jobs:
    checks:
        runs-on: ubuntu-latest
        name: Checks
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: Run Rector
              run: vendor/bin/rector process --dry-run

            - name: Run PHP-CS-Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --memory-limit=512M

            - name: Run Deptrac (bounded contexts)
              run: vendor/bin/deptrac analyse -c deptrac_bc.yaml --fail-on-uncovered --report-uncovered --no-progress

            - name: Run Deptrac (hexagonal layers)
              run: vendor/bin/deptrac analyse -c deptrac_hexa.yaml --fail-on-uncovered --report-uncovered --no-progress

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest

        services:
            database:
                image: postgres:16-alpine
                env:
                    POSTGRES_USER: app
                    POSTGRES_PASSWORD: '!ChangeMe!'
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: Run tests
              run: bin/phpunit
              env:
                  DATABASE_URL: 'postgresql://app:!ChangeMe!@localhost:5432/app?serverVersion=16&charset=utf8'
